baseURL: "https://jordanmitacek.com"
theme: "terminalcv"
title: "jordanmitacek.com"

params:
  version: "1.0.0"
  description: "My personal site"
  blog: true
  prompt:
    core:
      text: "jordan@irl"
      color: "purple"
      before: "["
      beforeColor: "red"
      after: '\]'
      afterColor: "red"
      # separator: '-'
    separator:
      text: "-"
      # color:
    path:
      before: "["
      beforeColor: "red"
      text: "~/mysite"
      color: "gray"
      after: '\]'
      afterColor: "red"
    extra:
      text: ": "
      color: "orange"

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  listLS: true
  #exitLocation: "about:blank"
  exitMessage: "[Session completed, the browserwindow can be safely closed]"
  source: true
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: |
    ‎   ___               _             
      |_  |             | |            
        | | ___  _ __ __| | __ _ _ __  
        | |/ _ \| '__/ _` |/ _` | '_ \ 
    /\__/ / (_) | | | (_| | (_| | | | |
    \____/ \___/|_|  \__,_|\__,_|_| |_|

    Welcome to my corner of the internet!

    Type 'help' for a list of available commands



  bootsequence: |
    User request detected
    Reserving Cloud Resources
    ............................
    Cloud Network ready
    ........
    Cloud Instance ready
    .......................
    Internet Breakout Ready, but Pong is preferred 

    Inititating CloudOS
    CloudOS Kernel Version 1.4.2: Sat February 29 23:21:41 CEST 2025; root:xnu-1699.22.73~1/RELEASE_ARM_64
    Loglevel = quiet
    ......
    ............
    ..................
    ........................
    ..............................
    ....................................

    Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
    The Regents of the University of California. All rights reserved.

    Copyright 2024, 2025
    TerminalCV. MIT License (MIT)

    [CloudOSBoot1]: ready
    [CloudOSBoot2]: ready
    [Webserver]: ready 
    [HUGO]: ready
    [TerminalCV]: ready

    Boot Complete, accepting user input.

  whois:
    # settings:
    #   useLess: true
    details:
      name: "Jordan Mitacek"
      profession: "CS Student"
      location: "Stony Brook University"
      email: "jordan.mitacek@gmail.com"
      homelink: "https://jordanmitacek.com"
      description: |
        Interested in low level systems and graphics
        I like playing games and I am a musician
        also... I use Arch BTW

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: "github"
        url: "https://github.com/JMit-dev"
      - name: "linkedin"
        url: "https://linkedin.com/in/jordanmitacek"
      - name: "discord"
        url: "https://discord.com/users/270323675327234048"

  work:
    # settings:
    #   useLess: true
    details:
      - jobTitle: Undergraduate Research
        color: gray
        company: "Stony Brook University"
        location: Stony Brook, NY
        date: February 2025 - Present
        description: |
          Simulating recursive portals in real-time with OpenGL, mesh shaders, and stencil buffer sorcery!
          Pushing hardware to its limits to make teleportation trivial.
          It’s like Portal, but I wrote it!

      - jobTitle: SULI Reasearch Internship
        color: gray
        company: "Brookhaven National Laboratory"
        location: Upton, NY
        date: June 2025 - August 2025
        description: |
          Integrated Bluesky Queue Server into Phoebus, so scientists can run beamline experiments like it’s a playlist.
          Built a REST + ZeroMQ bridge that streams live experimental data with sub-second latency.
          One app to run the beamline, see the results, and hit pause if the sample misbehaves.

      - jobTitle: CCI Research Internship
        color: gray
        company: "Brookhaven National Laboratory"
        location: Upton, NY
        date: August 2024  - December 2024
        description: |
          Built a Python interpreter for a deposition chamber’s custom scripting language (yes, really).
          Hooked it into EPICS and Bluesky so scientists could write macros and hit “run.”
          Also made a Qt GUI to watch the magic happen, real-time!

      - jobTitle: Computer Science Tutor
        color: gray
        company: "Suffolk County Community College"
        location: Selden, NY
        date: October 2023 - May 2024
        description: |
          Debugging segfaults, recursion, and existential dread—one student at a time.
          Helped students conquer C, Java, data structures, and their fear of debuggers.
          Office hours = therapy with code examples.

      - jobTitle: Undergraduate Resarch
        color: gray
        company: "Suffolk County Community College"
        location: Selden, NY
        date: November 2022 - May 2023
        description: |
          Built a data collection device with a Raspberry Pi, touchscreen GUI, 3D-printed housing, and custom sensors.
          Measured ion concentration and flow rate using Hall effect magic and some spinning magnets.
          Presented the project at SURC with a poster and walked out with the I-SUCCESS Award.

      - jobTitle: IT Technician
        color: gray
        company: "Staples"
        location: Patchogue, NY
        date:  June 2022 - August 2024
        description: |
          Installed SSDs, cleaned viruses, and resurrected customer laptops with a sigh and some compressed air.
          Taught non-tech folks how not to delete their OS and smiled through printer troubleshooting.
          Made Staples tech support feel like your favorite corner repair shop.

  education:
    details:
      - courseName: Stony Brook University
        color: gray
        date: September 2024 - May 2026
        description: "B.S. Computer Science - GPA: 3.26 / 4.0"

      - courseName: Suffolk County Community College
        date: September 2022 - May 2024
        description: "A.S. Computer Science - GPA: 3.9 / 4.0"

  skills:
    # settings:
    #   useLess: true
    details:
      - name: Systems Programming
        description: C, C++, MIPS/x86 Assembly, POSIX/Linux APIs, multithreading, sockets — the low-level stuff that keeps things fast and real.

      - name: Graphics & Multimedia
        description: OpenGL, GLSL, SDL2, GLFW, ImGui, OpenAL, Renderdoc — real-time rendering, audio, UI overlays, and GPU debugging with RenderDoc.

      - name: Tooling & Workflow
        description: Make, CMake, Bash, Python, Lua, Git, GDB, Valgrind, Criterion, Doxygen, tmux, Vim, LaTeX — my daily driver toolkit.

      - name: Web Development
        description: Java, Spring Boot, JavaScript, React, TypeScript, Python, Flask, HTML/CSS, Tailwind — building clean backends and responsive frontends.

      - name: Databases
        description: PostgreSQL, MySQL, MongoDB, SQLite — writing queries, designing schemas, and keeping data sane.

      - name: Scientific Computing
        description: Python, EPICS, Bluesky, Bluesky Queue Server, Ophyd, NumPy, pandas, xarray, scikit-learn, matplotlib — scripting, analyzing, plotting, and controlling real lab hardware.

      - name: Testing & Documentation
        description: Criterion, JUnit, Pytest, Doxygen, JavaDoc, Sphinx — I write code, then prove it works and document it like I mean it.  
  projects:
    details:
      - title: Odin
        color: red
        date: Since June 2025
        link: https://github.com/JMit-dev/Odin
        description: My custom OpenGL rendering library. Is it a framework? A sandbox? A mistake? Only the gods know.

      - title: Dot Matrix With Stereo Sound
        color: red
        date: Since June 2025
        link: https://github.com/JMit-dev/DMWSS
        description: A Game Boy emulator written in C++ with OpenGL. Accurate, fast, and plays Pokémon like it’s 1999.

      - title: OpenGL Portal Demo
        color: red
        date: April 2025 - May 2025
        link: https://github.com/JMit-dev/GL_Portal
        description: Real-time recursive portals using stencil buffers and camera transforms. Inspired by *Portal*, powered by OpenGL.

      - title: termplayer
        color: red
        date: September 2024
        link: https://github.com/JMit-dev/termplayer
        description: A full-featured ASCII video player for the terminal — uses ffmpeg, ytdlp, and curses to play video *with audio* in raw text.

      - title: Neovim config
        color: red
        date: Since September 2024
        link: https://github.com/JMit-dev/neovim-config
        description: A highly tuned Neovim config based on Kickstart.nvim — fast startup, smart keybinds, and no bloat.

      - title: Intel 8080 space invaders cabinet emulator
        color: red
        date: August 2024
        link: https://github.com/JMit-dev/i8080-spaceinvaders-emulator
        description: A full Intel 8080 emulator that runs the original Space Invaders arcade ROM

      - title: Course Assigner
        color: red
        date: September 2023 - October 2023
        link: https://github.com/JMit-dev/CourseAssigner
        description: Automated SCCC’s notoriously messy professor-course matching spreadsheet. JavaFX GUI, Excel parser.

      - title: WordWeaver
        color: red
        date: April 2023
        link: https://github.com/JMit-dev/WordWeaver
        description: A JavaFX chatbot that uses a Markov chain model to generate eerie, pseudo-intelligent responses.

      - title: Linux dotfiles
        color: red
        date: Since August 2022
        link: https://github.com/JMit-dev/dotfiles
        description: My Arch-based Linux setup. Includes riced dwm config, custom scripts, Vim, tmux.
